[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx.stdout.log
stderr_logfile=/var/log/nginx.stderr.log
priority=10

[program:certbot-renew]
command=sh -c 'while true; do /usr/local/bin/certbot-renew.sh; sleep 12h; done'
autostart=true
autorestart=true
stdout_logfile=/var/log/certbot.stdout.log
stderr_logfile=/var/log/certbot.stderr.log
priority=20

[program:php-fpm]
command=php-fpm83 -F
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm.stdout.log
stderr_logfile=/var/log/php-fpm.stderr.log
priority=5
