[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx.stdout.log
stderr_logfile=/var/log/nginx.stderr.log
priority=10

[program:php-fpm]
command=php-fpm83 -F
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm.stdout.log
stderr_logfile=/var/log/php-fpm.stderr.log
priority=5
